Repository 0oWoodenDooro0/MahjongAI, pull requests merged in 2024-12, with the labels that each got.

#7 Whitecat
  .gitignore
  majhong.py
  tile.py
Labels: enhancement

#8 pong and kong bug fixed
  majhong.py
Labels: bug

#9 Fix tile bug
  board.py
  game.py
  player.py
  tile.py
Labels: enhancement

#10 Add unittest
  test/__init__.py
  test/test_board.py
  test/test_game.py
  test/test_player.py
Labels: test

#11 Add chou pong kong to player
  board.py
  game.py
  player.py
  test/test_board.py
  test/test_game.py
Labels: enhancement

#19 Change file name
  mahjong/__init__.py
  mahjong/board.py
  mahjong/game.py
  mahjong/player.py
  mahjong/tile.py
  mahjong/util.py
  tests/test_board.py
  tests/test_game.py
  tests/test_mahjong.py
  tests/test_player.py
Labels: documentation

#23 修改之前pull request
  mahjong/board.py
  mahjong/game.py
  mahjong/player.py
  mahjong/tile.py
  mahjong/util.py
Labels: documentation

#26 change board draw func
  mahjong/board.py
  tests/test_board.py
Labels: enhancement

#28 change player func
  mahjong/player.py
  tests/test_player.py
Labels: enhancement

#27 change util check func
  mahjong/util.py
  tests/test_util.py
Labels: enhancement

#29 add closed kong change declaration datatype
  mahjong/board.py
  mahjong/player.py
  mahjong/tile.py
  mahjong/util.py
  tests/test_board.py
  tests/test_player.py
  tests/test_util.py
Labels: enhancement

#30 finish simple mahjong test board game player
  agent/__init__.py
  agent/run.py
  mahjong/board.py
  mahjong/game.py
  mahjong/player.py
  tests/test_board.py
  tests/test_game.py
  tests/test_player.py
Labels: enhancement
